### ISSUE TITLE
Link to this .HDA image is not working

### ISSUE THREAD

**Issue by Stefan-van-Hattum** [BlueSCSI/BlueSCSI-v2#114]
In the manual under "Using MacTCP" 
1. Load [this .HDA image](https://mega.nz/file/4kpDkQAb#-EEw3HZRrHOgDmK9qKRrM-zrh9OIg55gXgQn6T_JCXM) to your BlueSCSI, it has the following software installers:

The link provided is giving an error "The file could not be loaded" 
Tried different browsers from different computers.

**Comment by erichelgeson** [comment]
I just checked the link on bluescsi.com and on the wiki - both work fine. The link in this issue also is fine. Could you provide more details on what error you're getting?

**Comment by Stefan-van-Hattum** [comment]
Ok thank you for confirming the link is ok.
I just tried on my game PC and installed the Mega Desktop application and I am able to download the image now.

**Comment by erichelgeson** [comment]
Glad you got it working, though I've never used their desktop app. Works fine on windows/mac/linux (i just tested) - firefox and chrome.
