### ISSUE TITLE
No response from BlueSCSI web on Orders placed.

### ISSUE THREAD

**Issue by keysofc** [BlueSCSI/BlueSCSI-v2#153]
Placed an order though account created at Eric Helgeson's Bluescsi web and could not log in with email address used to create and pay for order. Sent email to erichelgeson+bluescsi@gmail.com and haven't gotten a response back on log in issue and order status. Hopefully there is a reasonable explanation for the delay in responding.

**Comment by erichelgeson** [comment]
Your email message went to spam - 
![image](https://github.com/BlueSCSI/BlueSCSI-v2/assets/271734/f0428818-078d-4fea-9e7a-05b6cd455b29)

Will reply in a few minutes to that message. Thanks.
