### ISSUE TITLE
ACT LED disabled on v2024.09.15 firmware?

### ISSUE THREAD

**Issue by mzryz** [BlueSCSI/BlueSCSI-v2#194]
I'm just wondering if this is normal? I just updated from v2023.10.12 to v2024.09.15 (yeah a big jump) and the ACT LED doesn't flash at all. It used to flash on SCSI HDD access & Daynaport access, but now it doesn't do anything at all.

**Comment by mzryz** [comment]
Update: just flashed my second BlueSCSI v2 in another machine, no issue with the ACT light there. All behaves normally. Must be a problem with my first unit.

**Comment by erichelgeson** [comment]
ACT LED is tied to the BUSY line on the SCSI bus, so firmware can't affect that (unless you're talking about the LED on the Pico)
