### ISSUE TITLE
Fisher Rosemount RS3 (Emerson)

### ISSUE THREAD

**Issue by pud469** [BlueSCSI/BlueSCSI-v2#20]
Have not tried Blue yet on RS3 console.  (Old DCS HMI)  I have tried SCSI2SD, and it really makes the console unusable and actually somehow damaged some of the (graphic) hardware. As replacements parts are not made, I would like to not do this again with trying Blue. Debugging on the console side is very difficult as it's proprietary software.  To continually support this system, we have use old 2.1GB Apple drive pulls to run. I was wondering if there is any information, I can provide to potentially mitigate damaging the hardware again. We are upgrading to SCSI2CF, currently being sold for the replacement on the RS3 consoles.  However, I would like to have other options, and also offer those options to community members.  I'm not a big fan of putting all my eggs in 1 basket as it limits resources and being held to the limitations of 1 company's resources.  I currently use 2 of their SCSI2CF mad for RS3 and they work great, So based on a software/firmware side I know it is a possible venture.  Again if there is anything I can provide to bring RS3 into the compatibility list, I would greatly do so.  I hope anyone understands my reservations of just trying the device as I have already had to replace a $5k video generation OI card and that was a few years ago. (The RS3 name for the GPU)

**Comment by erichelgeson** [comment]
Though thinking about it a bit I'm not sure how that happened without more details on what actually failed (and I'm not familiar with this RS3). V2 I'd say is well protected from any electrical issues, does not provide back power by default to the bus, and runs at 2.85v signaling. The schematics are provided if someone who is more familiar with the RS3 and the failure wanted to look too. Sorry I can't be of more help.

**Comment by pud469** [comment]
No problem, I wish I can give you better information.  This system is 1984 old, and any documentation around the hardware is lacking at best.  I would think reverse engineering would be in order and that is way beyond my abilities.  The only thing I can possibly pull from nothing, is that the data rate is somehow too slow, causing corruption.  That doesn't really explain why the video card took a poop. It could have just been its time and a coincidence. Maybe its was a heat issue trying to display corrupted or unavailable information.  I think I can get the firmware from the SCSI2CF adapter if that information is possibly useful, but I wouldn't expect you to spend much time with it, or even at all.  I can say that the SD card is faster than the bus speed so, it could possibly be something during the conversion, but since most apple computer handle this fine I don't see why it would be an issue here.  The CPUs on the consoles are 68MC0X0 series so they do not have a memory controller, but again that shouldn't be an issue with the SCSI interface.  
Let me know if you are interested in the firmware of the SCSI2CF and I'll even send some pics of the adapter hardware.  I know you do this as an open source project, but since there are still large corporations that rely on this old hardware.............If there are some changes needed in the firmware, you would be able to sell it, as this would be used for large profit from companies and just not a hobby.  I appreciate the work you are doing, the response, and making my Mac SE quiet.  I wish I had the time and knowledge to help with development, but maintaining 1984 technology in 2023, consumes quite a bit of my time.  Just a fun note that the operation console still refers to the hard drive as a "Winchester Drive", which I may still have one of those old things in a stash of parts.  As we push the limits of this hardware, we definitely use its limit of 2.1GB.  I do not think anyone should be using something this old at this point, but as we have been migrating to newer products over the last 5 years, the programming take a lot of time and money to translate.  Specifically from all the tricks to push its limitations. Thanks again for your time.
Justin    On Saturday, April 1, 2023 at 04:00:43 PM CDT, Eric Helgeson BlueSCSI.com ***@***.***> wrote:  
 
 


Though thinking about it a bit I'm not sure how that happened without more details on what actually failed (and I'm not familiar with this RS3). V2 I'd say is well protected from any electrical issues, does not provide back power by default to the bus, and runs at 2.85v signaling. The schematics are provided if someone who is more familiar with the RS3 and the failure wanted to look too. Sorry I can't be of more help.

**Comment by erichelgeson** [comment]
Hi, sorry we couldnt make more progress - I'll close this issue for now, but if you have any questions or details to provide in the future please don't hesitate to ask here.

**Comment by pud469** [comment]
I'm sorry, i forgot about this, as another solution to this was made.  There were a few articles on the hardware scsi2cf.  They sold drives specifically for Rosemount RS3, and as much as I would like to use this as a less expensive option, I completely forgot about this issue.  If I find to to to make documentation around the scsi controllers hardware I will be sure to include it, as it would expand on the compatibility of this project. 

    On Tuesday, May 21, 2024 at 08:08:06 PM CDT, Eric Helgeson ***@***.***> wrote:  
 
 


Hi, sorry we couldnt make more progress - I'll close this issue for now, but if you have any questions or details to provide in the future please don't hesitate to ask here.
