### ISSUE TITLE
New Feature: Dynaport SCSI Network Card Emulation

### ISSUE THREAD

**Issue by schreinerman** [BlueSCSI/BlueSCSI-v2#22]
PiSCSI can emulate a Dynaport SCSI Network Card. 

If BlueSCSI is used with Pico W, something similar could also work for BlueSCSI.

**Comment by erichelgeson** [comment]
This is now in beta https://github.com/BlueSCSI/BlueSCSI-v2/wiki/WiFi-DaynaPORT

**Comment by schreinerman** [comment]
Tested today and what to say: works great with my PowerBook 170!

**Comment by schreinerman** [comment]
Maybe some comment: I have the BlueSCSI v2 running in my Powerbook 170 and switching the SD-Card is somehow challenging 😉. It would be great, if there would be the possibility to backup the HDD files via WiFi to a FTP / WebDAV server or otherwise to provide an FTP / WebDAV server on the RP2040. Anyhow that's a very high-level request...

**Comment by erichelgeson** [comment]
https://github.com/BlueSCSI/BlueSCSI-v2/releases/tag/v2023.10.12
