### ISSUE TITLE
BlueSCSI.ini documentation CHS values

### ISSUE THREAD

**Issue by z80micro-mc** [BlueSCSI/BlueSCSI-v2#32]
How do I specify CHS parameters in Bluescsi.ini?

The example comments:

number of heads:  'HeadsPerCylinder=4'
sectors per track:   'SectorsPerTrack=33'

but omits details on number of cylinders!

Peter

**Comment by erichelgeson** [comment]
Cylinders is calculated here https://github.com/BlueSCSI/BlueSCSI-v2/blob/main/lib/SCSI2SD/src/firmware/geometry.c#L83 - I'm guessing - Do you have a situation where you'd need to set cylinders where it would not match that calculated value?

**Comment by z80micro-mc** [comment]
I am looking at what sets the values in physical geometry for page 4 for 'modeSense' and 'modeSelect' coomands.

Peter

**Comment by erichelgeson** [comment]
Right, that method is called for page 4 -https://github.com/BlueSCSI/BlueSCSI-v2/blob/main/lib/SCSI2SD/src/firmware/mode.c#L421

**Comment by erichelgeson** [comment]
If you have any other questions on CHS feel free to re-open or reply here (or open a new issue/discussion)
