### ISSUE TITLE
BlueSCSI Transfer Utility problem

### ISSUE THREAD

**Issue by karelfrydrych** [BlueSCSI/BlueSCSI-v2#39]
Hello, i have a problem with Transfer Utility. 

When i open blue transfer utility on Macintosh SE FDHD i get only: No compatibibile BlueSCSIs Found...

I have image created in Disk Jockey. 
I have BlueSCSI-V2 Desktop version. 
fimware from log: [10ms] FW Version: 2023.04.10-dev May 11 2023 02:01:14

Can someone please tell me what I am doing wrong?

**Comment by AiGeekNet** [comment]
Is your Transfer Utility for BlueSCSI V2 ?  There are some beta version of Transfer Utility for BlueSCSI V1 only, and more any release version of Transfer Utility now untill new release come within next BlueSCSI V2 firmware as I know.
