### ISSUE TITLE
Missing resistor values in schematic and BOM.

### ISSUE THREAD

**Issue by hadn69** [BlueSCSI/BlueSCSI-v2#51]
Some of the resistors for Desktop 50pin are missing values. The affected resistors are: 
R1
R2
R3
R4
R5
R6
R7
R8
R9
R10
R33
R34
R35
R36
R37
R38
R39
R40

**Comment by erichelgeson** [comment]
Spot checked a few and they do appear to be in the BOM - https://github.com/BlueSCSI/BlueSCSI-v2/blob/main/cc-nc-hardware/Desktop_50_Pin/ProductionFiles_JLCPCB/Desktop_50_Pin_TopConn_BOM.csv#L10 - R1, R2 etc

**Comment by erichelgeson** [comment]
It's been a few weeks so I'll close this, but if you have any other ideas or suggestions or would like to open a PR with those values added to the KiCAD files please feel free!
