### ISSUE TITLE
2023-07-03 firmware crashed with existing ROM disk

### ISSUE THREAD

**Issue by crackmonkey** [BlueSCSI/BlueSCSI-v2#53]
I upgraded a DB25 BlueSCSI v2-2022.12ato the 0223-07-03 firmware using BlueSCSI_Pico_2023-07-03_46af79d1.uf2. After drag & dropping the .uf2 file the PICOBOOT drive disappeared as expected but the USB device didn't reconnect and I got a continuous stream of flashes of the Pico's green LED. Eventually Windows complained that the USB device wasn't recognized. If there was a pattern to the blinking I didn't recognize it. 
Pulling the SD card to the Windows machine I did the flashing from shows the attached err.txt. Disabling the ROM disk using `DisableROMDrive=1` in the INI file go it working again, as well as creating a CLEAR_ROM file to delete the ROM disk.
[err.txt](https://github.com/BlueSCSI/BlueSCSI-v2/files/11992297/err.txt)

Recreating the ROM drive from the same image brings back the crash:
`== Loading ROM drive from /HD5.rom for ID: 5
---- SCSI ID: 5 blocksize 512 type 0
---- ROM drive maximum size is 1732608 bytes, image file is 1732608 bytes
---- ROM drive programming successful, image file renamed to /HD5.rom_loaded
`

**Comment by erichelgeson** [comment]
Found the source of the issue doing a git bisect from last release - I'll need to add a special case in for ROM in the new Platform Hook - you can keep the ROM in the current version by disabling the platform hooks in bluescsi ini `DisableConfigHook=1` till next release. Thanks for the report!
