### ISSUE TITLE
Power led is discontinued in the LCSC site (part number C2290) 

### ISSUE THREAD

**Issue by plaes** [BlueSCSI/BlueSCSI-v2#54]
When setting up a BOM on LCSC site, I stumbled upon a "discontinued" part which is affecting C2290 (power led).
Could you please share some details of the led used so we could pick up an alternative?

Also, would you be accepting alternatively some other distributors (Mouser for example) part numbers as well? (Or how/where are the BOM referenced maintained?)

**Comment by erichelgeson** [comment]
Per @androda's comment I'll close this but please feel free to re-open or comment if you still have questions!
