### ISSUE TITLE
Latest firmware crash (BlueSCSI_Pico_2023-07-03_46af79d1.bin)

### ISSUE THREAD

**Issue by xnop** [BlueSCSI/BlueSCSI-v2#56]
Hi,
Trying to update from version 2023.01.25 to v2023.07.03 and got the file "err.txt":

[10ms] Platform: BlueSCSI Pico
[10ms] FW Version: 2023.01.25-release Jan 25 2023 08:22:29
Flash chip size: 2048 kB
[10ms] Bootloader version: Jan 25 2023 08:22:29 BlueSCSI Pico
[201ms] Found firmware file: BlueSCSI_Pico_2023-07-03_46af79d1.bin
[202ms] DBG Writing flash at offset 0x00020000 data 0x00 0xC0 0x03 0x20 

++ MbedOS Fault Handler ++

FaultType: HardFault

[err.txt](https://github.com/BlueSCSI/BlueSCSI-v2/files/12248589/err.txt)
[log.txt](https://github.com/BlueSCSI/BlueSCSI-v2/files/12248591/log.txt)

Same error with version "v2023.04.10".

Then I tried to rollback to version "v2023.01.25" and seems to work again, see the log file with debug enabled.

Cheers,
Daniel

PS: Hardware version 2022.12a

**Comment by erichelgeson** [comment]
Thanks for the report - There was an issue in the 2023.01.25 release so you will need to flash via USB (dont worry, it's easy) https://github.com/BlueSCSI/BlueSCSI-v2/wiki/Updating-Firmware#usb-method
