### ISSUE TITLE
Attempt to use Spotlight index files

### ISSUE THREAD

**Issue by VitaliyYakob** [BlueSCSI/BlueSCSI-v2#69]
Hi,
Firmware v2023.08.10, created the CD2 directory when it placed the ISO images. macOS created Spotlight index files.
<img width="622" alt="IndexFiles" src="https://github.com/BlueSCSI/BlueSCSI-v2/assets/38102260/7bc546c1-7eee-405c-829c-c41b7b9eecbe">

When change the image in a vintage Mac, an index file is inserted.

<img width="630" alt="SwitchToIndex" src="https://github.com/BlueSCSI/BlueSCSI-v2/assets/38102260/babf244f-d091-46f1-95a4-2244a5dad33d">

Of course, Mac OS can't read such a "image" of the disk

![DiskInitialize](https://github.com/BlueSCSI/BlueSCSI-v2/assets/38102260/396d120c-f177-4d80-9602-0c03a90ab0f9)

**Comment by erichelgeson** [comment]
Hi! This is a dupe of #64 - There is a patch that will be in the next release. If you'd like to test it out click on "Releases" in github and download the Nightly one.

**Comment by VitaliyYakob** [comment]
Oh, sorry. I didn't notice it.
Thanx.
