### ISSUE TITLE
Source code for BlueSCSI-Toolbox supporting firmware version appears missing

### ISSUE THREAD

**Issue by d235j** [BlueSCSI/BlueSCSI-v2#72]
Hi,

It appears that the source code for the beta firmware version that supports the BlueSCSI Transfer Utility / Toolbox is completely missing. As the BlueSCSI firmware source code is distributed under the GPL 3.0, and the copyright is not entirely owned by the BlueSCSI team (as BlueSCSI is forked from and depends on code written by others), it is necessary for this source code to be available to comply with the terms of the GPL.

The binary firmware packages can be found at 
https://github.com/erichelgeson/BlueSCSI-Toolbox/releases/tag/v20220927-BETA1 for BlueSCSI v1
and https://github.com/erichelgeson/BlueSCSI-Toolbox/releases/tag/beta2 for BlueSCSI v2.

While there are apparent links to source code on those release pages, they only contain a `README.md` file.

This is probably best resolved by uploading snapshots of the source code used to make those builds to the above release pages. This could also be resolved by including license text, attribution, and an offer for the source code in the release zips (which is already required per the terms of the GPL); and ideally on the release page as well.

**Comment by erichelgeson** [comment]
You can find the code under the `eric/toolbox` branch and the ticket for doing the same for v1 https://github.com/erichelgeson/BlueSCSI/issues/254 which I hope to get to this weekend or next, pending IRL responsibilities.
